#!/usr/bin/env ruby

require 'vantiv'
require 'vantiv/certification/validation_test_runner'
require 'optparse'

options = {}
parser = OptionParser.new do |opts|
  opts.banner = "Usage: vantiv-certify-app [--filter_by <test_name>]"

  opts.on("--filter_by [TEST_NAME]", "Filter which certifications to run") do |filter|
    options[:filter_by] = filter
  end
end

parser.parse!

require "dotenv"
Dotenv.load
Vantiv.configure do |config|
  config.environment = Vantiv::Environment::CERTIFICATION
  config.merchant_id = ENV["MERCHANT_ID"]
  config.default_order_source = "ecommerce"
  config.paypage_id = ENV["PAYPAGE_ID"]

  config.user = ENV["VANTIV_USER"]
  config.password = ENV["VANTIV_PASSWORD"]

  config.default_report_group = '1'
end


Vantiv::Certification::ValidationTestRunner.run(
  save_to: "certs.txt",
  filter_by: options[:filter_by]
)

%x(open certs.txt)
